# Data cleaning in pandas

* check for any duplicates and any remove them

* Standardize data and fix error

In [18]:
import pandas as pd

In [19]:
df=pd.read_excel("Data sets\ccl.xlsx")

In [20]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [22]:
df.iloc[20]

CustomerID                                  1020
First_Name                                Anakin
Last_Name                              Skywalker
Phone_Number                        876|678|3469
Address              910 Tatooine Road, Tatooine
Paying Customer                              Yes
Do_Not_Contact                                 N
Not_Useful_Column                           True
Name: 20, dtype: object

In [23]:
df.tail(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [24]:
fd=df.duplicated()

In [25]:
fd

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [26]:
df[fd]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [27]:
df.drop_duplicates(inplace=True)

In [28]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [29]:
#for checking duplicates
df.duplicated().sum()

np.int64(0)

In [30]:
df['Last_Name']=df['Last_Name'].str.strip("123._/")

In [31]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [32]:
 df['Phone_Number'].str.replace("[^a-zA 0-9]","",regex=True)

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8              a
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18             a
19    8766783469
Name: Phone_Number, dtype: object

In [33]:
str(df['Phone_Number'][17])[3:6]+'-'+str(str

_IncompleteInputError: incomplete input (4133187508.py, line 1)

In [ ]:
df['Phone_Number'] = df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [ ]:
#python strin
name = "mike-tyson"
name = name.replace("-","")

# mike/tyson

name[0:4]+"/"+name[4:]

'mike/tyson'

# apply() => Apply is a pandas function  which will apply specificied functionality to each value of series

In [ ]:
df['Phone_Number'] = df['Phone_Number'].apply(lambda x:str(x))

In [ ]:
df['Phone_Number']

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18
19    8766783469
Name: Phone_Number, dtype: object

In [ ]:
type(df['Phone_Number'])

pandas.core.series.Series

In [ ]:
df['Phone_Number'] = df['Phone_Number'].str.replace("[^0-9]","",regex=True)

# abc-def-ghij

In [ ]:
l1=lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10]
l1("1234567890")

'123-456-7890'

In [ ]:
df['Phone_Number'] = df['Phone_Number'].apply(l1)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
## address
df['Address'].str.split(',')

0                      [123 Shire Lane,  Shire]
1                         [93 West Main Street]
2                          [298 Drugs Driveway]
3     [980 Paper Avenue,  Pennsylvania,  18503]
4                            [123 Dragons Road]
5                            [768 City Parkway]
6                           [1209 South Street]
7                               [98 Clue Drive]
8                            [123 Middle Earth]
9                 [25th Main Street,  New York]
10                     [612 Shire Lane,  Shire]
11                       [2394 Hogwarts Avenue]
12                           [2039 Main Street]
13                           [343 City Parkway]
14                              [214 HR Avenue]
15                       [2395 Hogwarts Avenue]
16            [121 Paper Avenue,  Pennsylvania]
17                            [3498 Super Lane]
18                                        [N/a]
19               [910 Tatooine Road,  Tatooine]
Name: Address, dtype: object

In [ ]:
 df['Address'].str.split(',',expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [ ]:
df[['street_Address','city','pin_code']]=df['Address'].str.split(',',expand=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_Address,city,pin_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [ ]:
df['Paying Customer']=df['Paying Customer']..str.replace('Yes','Y')

In [ ]:
 df['Paying Customer']=df['Paying Customer'].str.replace('No','N')

In [ ]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')

In [ ]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')

In [ ]:
# Remove columns
df.drop(columns=['Not_Useful_Column','Address'],inplace=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,Yes,No
1,1002,Abed,Nadir,123/643/9775,No,Yes
2,1003,Walter,White,7066950392,N,NaN
3,1004,Dwight,Schrute,123-543-2345,Yes,Y
4,1005,Jon,Snow,876|678|3469,Y,No
5,1006,Ron,Swanson,304-762-2467,Yes,Yes
6,1007,Jeff,Winger,NaN,No,No
7,1008,Sherlock,Holmes,876|678|3469,N,No
8,1009,Gandalf,NaN,N/a,Yes,NaN
9,1010,Peter,Parker,123-545-5421,Yes,No
10,1011,Samwise,Gamgee,NaN,Yes,No
11,1012,Harry,Potter,7066950392,Y,NaN
12,1013,Don,Draper,123-543-2345,Yes,N
13,1014,Leslie,Knope,876|678|3469,Yes,No
14,1015,Toby,Flenderson,304-762-2467,N,No
15,1016,Ron,Weasley,123-545-5421,No,N
16,1017,Michael,Scott,123/643/9775,Yes,No
17,1018,Clark,Kent,7066950392,Y,NaN
18,1019,Creed,Braton,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,Yes,N

## Dealing with null values

In [ ]:
df.replace('N/a','',inplace=True)
df.replace('NaN','',inplace=True)

In [ ]:
df.replace('--','',inplace=True)

In [ ]:
df.fillna('',inplace=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,Yes,No
1,1002,Abed,Nadir,123/643/9775,No,Yes
2,1003,Walter,White,7066950392,N,
3,1004,Dwight,Schrute,123-543-2345,Yes,Y
4,1005,Jon,Snow,876|678|3469,Y,No
5,1006,Ron,Swanson,304-762-2467,Yes,Yes
6,1007,Jeff,Winger,,No,No
7,1008,Sherlock,Holmes,876|678|3469,N,No
8,1009,Gandalf,,,Yes,
9,1010,Peter,Parker,123-545-5421,Yes,No
10,1011,Samwise,Gamgee,,Yes,No
11,1012,Harry,Potter,7066950392,Y,
12,1013,Don,Draper,123-543-2345,Yes,N
13,1014,Leslie,Knope,876|678|3469,Yes,No
14,1015,Toby,Flenderson,304-762-2467,N,No
15,1016,Ron,Weasley,123-545-5421,No,N
16,1017,Michael,Scott,123/643/9775,Yes,No
17,1018,Clark,Kent,7066950392,Y,
18,1019,Creed,Braton,,,Yes
19,1020,Anakin,Skywalker,876|678|3469,Yes,N

In [ ]:
for i in df.index:
    if df.loc[i,'Do_Not_Contact']=="Y" or df.loc[i,'Phone_Number']==  
        df.drop(i,inplace=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_Address,city,pin_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [34]:
df.reset_index(inplace=True,drop=True)